replicaCount: 1

image:
  repository: nexuscr.factus.dk/chess-combat
  tag: "0.1.19"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: chess-combat.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

env:
  OPENAI_API_KEY_SECRET: openai-api-key
  GEMINI_API_KEY_SECRET: gemini-api-key
  POSTGRES_CONNECTION_SECRET: postgres-connection
