replicaCount: 1

# Application configuration
app:
  debug: false  # Set to true to enable debug logging

image:
  repository: nexuscr.factus.dk/chess-combat
  tag: "0.1.48"
  pullPolicy: IfNotPresent

# Image pull secrets
imagePullSecrets: []
# Example:
# imagePullSecrets:
#   - name: nexus-registry-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: chess-combat.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Secrets configuration
secrets:
  # OpenAI API Key secret
  openai:
    create: true                    # Set to false if using external secret (e.g., from Flux)
    secretName: openai-api-key      # Name of the secret (configurable for external secrets)
    keyName: api-key                # Key name within the secret
    apiKey: ""                      # Set this value when creating secret via Helm

  # Gemini API Key secret
  gemini:
    create: true                    # Set to false if using external secret (e.g., from Flux)
    secretName: gemini-api-key      # Name of the secret (configurable for external secrets)
    keyName: api-key                # Key name within the secret
    apiKey: ""                      # Set this value when creating secret via Helm

  # PostgreSQL connection secret
  postgres:
    create: true                              # Set to false if using external secret (e.g., from Flux)
    secretName: postgres-connection           # Name of the secret (configurable for external secrets)
    keyName: connection                       # Key name within the secret
    connectionUrl: ""                         # Set this value when creating secret via Helm (e.g., postgresql://user:password@host:5432/database)

# Override the name of the chart
nameOverride: ""
# Override the full name of the release
fullnameOverride: ""

# Service account configuration (if needed in the future)
serviceAccount:
  create: false
  name: ""
