apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chess-combat.fullname" . }}
  labels:
    {{- include "chess-combat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chess-combat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chess-combat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: chess-combat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.openai.secretName }}
                  key: {{ .Values.secrets.openai.keyName }}
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.gemini.secretName }}
                  key: {{ .Values.secrets.gemini.keyName }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgres.secretName }}
                  key: {{ .Values.secrets.postgres.keyName }}
            - name: DEBUG
              value: {{ .Values.app.debug | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
