apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
  labels:
    app: {{ include "chess-combat.name" . }}
type: Opaque
data:
  api-key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-api-key
  labels:
    app: {{ include "chess-combat.name" . }}
type: Opaque
data:
  api-key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-connection
  labels:
    app: {{ include "chess-combat.name" . }}
type: Opaque
data:
  connection: ""
