{{- if and .Values.secrets.openai.create .Values.secrets.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.openai.secretName }}
  labels:
    {{- include "chess-combat.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.openai.keyName }}: {{ .Values.secrets.openai.apiKey | b64enc | quote }}
{{- end }}
---
{{- if and .Values.secrets.gemini.create .Values.secrets.gemini.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gemini.secretName }}
  labels:
    {{- include "chess-combat.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.gemini.keyName }}: {{ .Values.secrets.gemini.apiKey | b64enc | quote }}
{{- end }}
---
{{- if and .Values.secrets.postgres.create .Values.secrets.postgres.connectionUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.secretName }}
  labels:
    {{- include "chess-combat.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.postgres.keyName }}: {{ .Values.secrets.postgres.connectionUrl | b64enc | quote }}
{{- end }}
