apiVersion: v1
kind: Service
metadata:
  name: {{ include "chess-combat.fullname" . }}
  labels:
    app: {{ include "chess-combat.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ include "chess-combat.name" . }}
