# GitHub Actions workflow for build/test
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Database Migration
      env:
        DATABASE_URL: "sqlite:///:memory:"
      run: |
        echo "Running database migration..."
        python migrate_db.py
        echo "Migration completed successfully!"

    - name: Run in-memory tests
      env:
        DATABASE_URL: "sqlite:///:memory:"
        OPENAI_API_KEY: "test_key_openai"
        GEMINI_API_KEY: "test_key_gemini"
      run: |
        # Run workflow integration tests first
        python -m pytest tests/test_workflow.py -v -s
        # Run CI-specific tests
        python -m pytest tests/test_ci.py -v
        python -m pytest tests/test_in_memory.py -v
        # Run all other tests except integration tests that require external services
        python -m pytest tests/ -v --ignore=tests/test_integration.py --ignore=tests/test_api_integration.py
