name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: nexus.factus.dk/chess-combat

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: chess
          POSTGRES_PASSWORD: chess
          POSTGRES_DB: chess
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Nexus Docker registry
        uses: docker/login-action@v3
        with:
          registry: nexuscr.factus.dk
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_USER_PW }}

      - name: Set DATABASE_URL env var
        run: echo "DATABASE_URL=postgresql://chess:chess@localhost:5432/chess" >> $GITHUB_ENV

      - name: Install Python and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create database tables
        run: |
          python -c "from app.db.models import Base; from app.db.crud import engine; Base.metadata.create_all(bind=engine)"

      - name: Run all tests (unit + integration)
        run: pytest

      - name: Get and bump version
        id: get_version
        run: |
          if git describe --tags --abbrev=0 2>/dev/null; then
            VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          else
            VERSION=$(grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+' VERSION.txt)
          fi
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo $NEW_VERSION > VERSION.txt
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push new version tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add VERSION.txt
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }}" || echo "No changes to commit"
          git tag v${{ steps.get_version.outputs.version }}
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin main --tags

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
