name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: nexus.factus.dk/chess-combat

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Nexus Docker registry
        uses: docker/login-action@v3
        with:
          registry: nexuscr.factus.dk
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_USER?PASSWORD }}

      - name: Run unit tests only (skip integration)
        run: pytest -m "not integration"

      - name: Get and bump version
        id: get_version
        run: |
          if git describe --tags --abbrev=0 2>/dev/null; then
            VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          else
            VERSION=$(cat VERSION.txt)
          fi
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo $NEW_VERSION > VERSION.txt
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push new version tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add VERSION.txt
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }}" || echo "No changes to commit"
          git tag v${{ steps.get_version.outputs.version }}
          git push origin main --tags

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
